config/routes.rb
Rails.application.routes.draw do
  # get 'project/index'
  # get 'project/update'
  # get 'project/create'
  get '/' => 'main#index'

  post 'main/update' => 'main#update'

  post 'main/create' => 'main#create'
  #post 'project/create' => 'project#create'
  #get 'main/index'
  #get 'main/create'
  #get 'main/update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @todo = Todo.all.sort {|a, b|b.created_at <=> a.created_at}
		@projects = Project.all

    respond_to do |format|
			format.html # index.html.erb
			format.json  { render :json => {:todo => @todo, :projects => @projects }}
		end

  end

  def create
    if (params[:title].empty?)
      Todo.create(text: params[:text], isCompleted: false, project_id: params[:project_id])
    else
      project = Project.create(title:params[:title])
      Todo.create(text: params[:text], isCompleted: false, project_id: project["id"])
    end
    redirect_to action: 'index'
  end

  def update
    todo = Todo.find(params[:todo_id])
		todo.isCompleted = !todo.isCompleted
		todo.save
		redirect_to action: 'index'
  end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
  end

  def update
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondTestRubyProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/create.html.erb
<h1>Main#create</h1>
<p>Find me in app/views/main/create.html.erb</p>

app/views/main/index.html.erb
<div id="addtaskflex">
  <div id="addtask">
    <h3>НОВАЯ ЗАДАЧА</h3>
    <hr id="delimeter" noshade>
    <%= form_tag(main_create_path, method: "post", id: "form") do %>
      <%= text_field_tag(:text, nil, placeholder: 'Название задачи...', class:'textfield') %>
      <div id="addproject">
        <%= text_field_tag(:title, nil, placeholder: 'Название категории...', class:'textfield') %>
      </div>
      <div id="select">
        <select name="project_id" id="project_id" style="width:100%;">
        <% @projects.each do |project| %>
          <%= options_for_select([[project["title"], project["id"]]]) %>
        <% end %>
        <option value="newctg">Новая категория</option>
        </select>
      </div>

      <div id="buttons">
        <a id="hide" href="#"><div id="cancel">ОТМЕНА</div></a>
        <%= link_to "#", id: "submit" do %>
          <div id="ok">ОК</div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div id="headline">
  <h1>Задачи</h1>
  <div id="plus">
      <%= image_tag("addIcon.png", :alt => "Новая задача") %>
  </div>
</div>



<div class="container">

  <div class="row" id="cards">
    <% @projects.each do |project| %>
      <div class="col-12 col-md-6 col-lg-4">
        <div id="todoCard">
          <h3><%= project["title"] %></h3>
          <hr id="delimeter" noshade>
          <ul>
            <% @todo.each do |task| %>
            <% if task["project_id"] == project["id"] then %>
              <%= form_tag(main_update_path, method: "post", id: task.id) do %>
                <%= hidden_field_tag 'todo_id', task.id %>
                <% if task.isCompleted == true then %>
                  <li><input type="checkbox" id="check" value="<%= task.id %>" checked><span id="completed"><%= task.text %></span></li>
                <% else  %>
                  <li><input type="checkbox" id="check" value="<%= task.id %>"><span id="uncompleted"><%= task.text %></span></li>
                <% end %>
              <% end %>
            <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/main/update.html.erb
<h1>Main#update</h1>
<p>Find me in app/views/main/update.html.erb</p>

app/views/project/create.html.erb
<h1>Project#create</h1>
<p>Find me in app/views/project/create.html.erb</p>

app/views/project/index.html.erb
<h1>Project#index</h1>
<p>Find me in app/views/project/index.html.erb</p>

app/views/project/update.html.erb
<h1>Project#update</h1>
<p>Find me in app/views/project/update.html.erb</p>